project_id = "tjuokxdkimrtyqsbzskj"

[functions.uazapi-proxy]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.process-scheduled-messages]
verify_jwt = false